name: shade_ui
description: A UI system for JappeOS apps.

publish_to: 'none'
version: 2.0.0+3

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  menu_bar: ^0.5.3
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: resources/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: resources/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
        - asset: resources/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: resources/fonts/Nunito/Nunito-LightItalic.ttf
          weight: 300
        - asset: resources/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: resources/fonts/Nunito/Nunito-Italic.ttf
          weight: 400
        - asset: resources/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: resources/fonts/Nunito/Nunito-MediumItalic.ttf
          weight: 500
        - asset: resources/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: resources/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
        - asset: resources/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: resources/fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 700
        - asset: resources/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: resources/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
        - asset: resources/fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: resources/fonts/Nunito/Nunito-BlackItalic.ttf
          weight: 900
